version: '3'
services:  
  DB_app:
    image: mariadb:latest
    container_name: DB_resource
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: passr
      MYSQL_DATABASE: hermes

  rabbit:
    image: rabbitmq:management-alpine
    container_name: rabbitmqOdeja
    ports:
      - "5672:5672"
      - "8080:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: passr    
    hostname: myrabbit    
  
  mongouser:
    image: mongo:latest
    container_name: mongoCategory
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: passr    

  mongoadmin:
    image: mongo-express:latest
    container_name: mongoadmin
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: passr
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: "mongoCategory"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "user"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "passr"


